CREATE TABLE IF NOT EXISTS iglesias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  activa BOOLEAN DEFAULT TRUE,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  reset_token VARCHAR(255) NULL,
  reset_token_expira TIMESTAMP NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre_completo VARCHAR(200) NOT NULL,
  correo VARCHAR(150) NOT NULL,
  codigo_postal VARCHAR(20) NOT NULL,
  edad INT NOT NULL,
  evento_descripcion VARCHAR(255) NULL,
  reconciliacion BOOLEAN DEFAULT FALSE,
  aceptar_cristo BOOLEAN DEFAULT FALSE,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE personas ADD COLUMN IF NOT EXISTS reconciliacion BOOLEAN DEFAULT FALSE;
ALTER TABLE personas ADD COLUMN IF NOT EXISTS aceptar_cristo BOOLEAN DEFAULT FALSE;

ALTER TABLE personas ADD COLUMN reconciliacion BOOLEAN DEFAULT FALSE;
ALTER TABLE personas ADD COLUMN aceptar_cristo BOOLEAN DEFAULT FALSE;
