CREATE TABLE IF NOT EXISTS iglesias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  activa BOOLEAN DEFAULT TRUE,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  reset_token VARCHAR(255) NULL,
  reset_token_expira TIMESTAMP NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre_completo VARCHAR(200) NOT NULL,
  correo VARCHAR(150) NOT NULL,
  telefono VARCHAR(50) NULL,
  codigo_postal VARCHAR(20) NOT NULL,
  edad INT NOT NULL,
  evento_descripcion VARCHAR(255) NULL,
  iglesia VARCHAR(150) NULL,
  voluntario VARCHAR(150) NULL,
  reconciliacion BOOLEAN DEFAULT FALSE,
  aceptar_cristo BOOLEAN DEFAULT FALSE,
  estado_actual VARCHAR(100) NULL,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE personas ADD COLUMN IF NOT EXISTS iglesia VARCHAR(150) NULL;
ALTER TABLE personas ADD COLUMN IF NOT EXISTS voluntario VARCHAR(150) NULL;
ALTER TABLE personas ADD COLUMN IF NOT EXISTS reconciliacion BOOLEAN DEFAULT FALSE;
ALTER TABLE personas ADD COLUMN IF NOT EXISTS aceptar_cristo BOOLEAN DEFAULT FALSE;
ALTER TABLE personas ADD COLUMN IF NOT EXISTS estado_actual VARCHAR(100) NULL;

CREATE TABLE IF NOT EXISTS estado_historial (
  id INT AUTO_INCREMENT PRIMARY KEY,
  persona_id INT NOT NULL,
  estado VARCHAR(100) NOT NULL,
  nota TEXT NULL,
  fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);

CREATE INDEX idx_estado_historial_persona ON estado_historial(persona_id);
